### ISSUE TITLE
IsCreditCardNumberValid returns false for valid card numbers

### ISSUE THREAD

**Issue by kakarotto67** [Yabko/CreditCardNumberValidator#2]
Pass the following card numbers into your IsCreditCardNumberValid method (they are all valid, check [this](https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm), [this](http://support.worldpay.com/support/kb/bg/testandgolive/tgl5103.html), and [this](http://www.securetrading.com/resources/test-card-numbers-2/)):
"3411 3411 3411 347"
"341134113411347"
"3434 3434 3434 343"
"343434343434343"
"3530 1113 3330 0000"
"3566 0020 2036 0505"
"3714 4963 5398 431"
"371449635398431"
"3782 8224 6310 005"
"378282246310005"
"4012 8888 8888 1881"
"4111 1111 1111 1111"
"4222222222222"
""4917610000000000003"
"5000 0000 0000 0611"
"5105 1051 0510 5100"
"555 5555 5555 4444"
Expected result: true (for each card number from above)
Actual result: false (for each card number from above)

**Comment by Yabko** [comment]
Fixed.
Note: 555 5555 5555 4444 (the last from your list) is not a valid number (checked in the online validator).

**Comment by kakarotto67** [comment]
I still receive **false** for these numbers:
"3411 3411 3411 347"
"3434 3434 3434 343"
"3530 1113 3330 0000"
"3566 0020 2036 0505"
"3714 4963 5398 431"
"3782 8224 6310 005"
"4012 8888 8888 1881"
"4111 1111 1111 1111"
"4222 2222 2222 2"
"5105 1051 0510 5100"

**Comment by Yabko** [comment]
my bad, should work now
