### ISSUE TITLE
Incorrect returned value of GetCreditCardVendor

### ISSUE THREAD

**Issue by kakarotto67** [Yabko/CreditCardNumberValidator#4]
Pass "35301113333000001" card number into your GetCreditCardVendor method
Expected result: exception or some message as that number isn't valid
Actual result: You've got a JCB card (yeah, and remove that "you've got a..."). But please pass this card number into your IsCreditCardNumberValid and it will return false, so how JCB can be returned as vendor?

**Comment by Yabko** [comment]
fixed

**Comment by kakarotto67** [comment]
I still have the issue: number "35301113333000001" shouldn't be valid, but **IsCreditCardNumberValid** returns true.

**Comment by Yabko** [comment]
Should be fixed now.
